services:
  export:
    image: "ghcr.io/tk42/firestore-import-export"
    command: ["node", "export.js", "collecton_name"]
    volumes:
      - ./serviceAccountKey.json:/home/serviceAccountKey.json

  import:
    image: "ghcr.io/tk42/firestore-import-export"
    command: ["node", "import.js", "./import-to-firestore.json"]
    volumes:
      - ./serviceAccountKey.json:/home/serviceAccountKey.json
      - ./import-to-firestore.json:/home/import-to-firestore.json
